# example .gitpod.yml from https://github.com/gitpod-io/demo-multi-repo-frontend
workspaceLocation: haven/main.code-workspace # Relative to /workspace dir
additionalRepositories:
    - url: https://github.com/thisisommore/xxdk-wasm.git
      checkoutLocation: xxdk-wasm

image:
  file: gitpod.Dockerfile
tasks:
    - name: xxdk-wasm
      # change working directory as per configured in `checkoutLocation`
      # which is configured above as `/workspaces/backend`
      before: |
          cat global.gitconfig >> /home/gitpod/.gitconfig
          cd ../xxdk-wasm
          go install github.com/agnivade/wasmbrowsertest@v0.10.0
          go install github.com/agnivade/wasmbrowsertest/cmd/cleanenv@v0.10.0
          mv $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec
          
          wget https://dl-ssl.google.com/linux/linux_signing_key.pub -O /tmp/google.pub
          sudo gpg --no-default-keyring --keyring /etc/apt/keyrings/google-chrome.gpg --import /tmp/google.pub
          echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update 
          sudo apt-get install -y google-chrome-stable


          # cleanenv -remove-prefix GITPOD_ -- go test -cover ./...
      init: |
          npm i && npm run build && bun link && gp sync-done xxdk-wasm-link

      # changing of working directory is not required as these tasks will
      # by default by executed in `/workspaces/demo-multi-repo-frontend`
    - name: haven
      init: |
          gp sync-await xxdk-wasm-link
          bun link xxdk-wasm
      command: |
          npm run dev
          
    - name: xxdk-wasm
      init: |
          cd /workspace
          git clone https://git.xx.network/elixxir/xxdk-wasm.git
          cd xxdk-wasm

    - name: client
      init: |
          cd /workspace
          git clone https://git.xx.network/elixxir/client.git
          cd client

    - name: ekv
      init: |
          cd /workspace
          git clone https://git.xx.network/elixxir/ekv.git
          cd ekv
