export const STATE_PATH = 'speakeasyapp';
export const CHANNELS_STORAGE_TAG = 'ELIXXIR_USERS_TAGS';
export const DMS_DATABASE_NAME = 'DMS_DATABASE_NAME';
export const PIN_MESSAGE_LENGTH_MILLISECONDS = 1.814e+9
export const MAXIMUM_PAYLOAD_BLOCK_SIZE = 725;
export const CHANNELS_WORKER_JS_PATH = '/integrations/assets/channelsIndexedDbWorker.js';
export const DMS_WORKER_JS_PATH = '/integrations/assets/dmIndexedDbWorker.js';
export const MESSAGE_LEASE = 30000;
export const CMIX_NETWORK_READINESS_THRESHOLD = 0.25;

export const DUMMY_TRAFFIC_MAXIMUM_MESSAGES_PER_CYCLE = 3;
export const DUMMY_TRAFFIC_DURATION_TO_WAIT_BETWEEN_SENDS_MILLISECONDS = 15000;
export const DUMMY_TRAFFIC_UPPERBOUND_INTERVAL_BETWEEN_CYCLES_MILLISECONDS = 7000;
export const DUMMY_TRAFFIC_ARGS = [
  DUMMY_TRAFFIC_MAXIMUM_MESSAGES_PER_CYCLE,
  DUMMY_TRAFFIC_DURATION_TO_WAIT_BETWEEN_SENDS_MILLISECONDS,
  DUMMY_TRAFFIC_UPPERBOUND_INTERVAL_BETWEEN_CYCLES_MILLISECONDS
] as [number, number, number]